version: '3'
services:
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: always
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./server/data:/data/db
    
  node:
    build: ./server
    container_name: crucigrama
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
