version: '3'
services:
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: always
    volumes:
      - ./server/data:/data/db
    networks:
      - crucigramas-network

  node:
    build: ./server
    container_name: crucigrama
    restart: always

    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=api.crucigramas.lafuentedanel.com
      - LETSENCRYPT_HOST=api.crucigramas.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - crucigramas-network
      - nginx-proxy

networks:
  crucigramas-network:
    name: crucigramas-network
  nginx-proxy:
    external:
      name: nginx-proxy
